#spring:
#  application:
#    name: user-consumer
#  #zipkin  上报信息
#  zipkin:
#    base-url: http://localhost:9411/
#    #采样比例1
#  sleuth:
#    sampler:
#      rate: 1
#  #admin
#  boot:
#    admin:
#      client:
#        url: http://localhost:5000
#server:
#  port: 3000
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8000/eureka/ #http://admin:123@localhost:8000/eureka/   #集群 http://localhost:8001/eureka/,http://localhost:8002/eureka/,http://localhost:8000/eureka/
#
#
#  #Feign默认支持Ribbon；Ribbon的重试机制和Feign的重试机制有冲突，所以源码中默认关闭Feign的重试机制,使用Ribbon的重试机制
#ribbon:
#  #连接超时时间(ms)
#  ConnectTimeout: 1000
#  #业务逻辑超时时间(ms)
#  ReadTimeout: 2000
#
#  #同一台实例最大重试次数,不包括首次调用
#  MaxAutoRetries: 1
#  #重试负载均衡其他的实例最大重试次数,不包括首次调用
#  MaxAutoRetriesNextServer: 1
#  #是否所有操作都重试
#  OkToRetryOnAllOperations: false
#
##启用hystrix
#feign:
#  hystrix:
#    enabled: true
#
#
##  #开启所有上报端口
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always
#      enabled: true
#
##默认线程池隔离  这里改成信号量隔离
##hystrix:
##  command:
##    default:
##      execution:
##        isolation:
##          strategy: SEMAPHORE
#
#
#
#
