#eureka 集群
#spring:
spring:
  application:
    name: springcloud-eureka
  profiles: server1
server:
  port: 8000
eureka:
  instance:
    hostname: server1   #自己本地在hosts文件中配置 server1
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server2:8001/eureka/,http://server3:8002/eureka/