spring:
  application:
    name: user-provider
  #zipkin 上报信息
  zipkin:
    base-url: http://localhost:9411/ #本地启动zipkin-server-2.12.8-exec.jar
    #采样比例1
  sleuth:
    sampler:
      rate: 1
  #admin
  boot:
    admin:
      client:
        url: http://localhost:5000
server:
  port: 2000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/ #http://admin:123@localhost:8000/eureka/   #集群 http://localhost:8001/eureka/,http://localhost:8002/eureka/,http://localhost:8000/eureka/4

#开启所有上报端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      enabled: true
