spring:
  application:
    name: springcloud-config
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/shootday/springcloud-configCenter  #git@github.com:shootday/springcloud-configCenter.git 用这个地址会进行ssh校验
#          search-paths: /**  # 指定搜索根路径下的所有目录，若有多个路径使用逗号隔开
#          username:
#          password:
          basedir: F:\gitRep\springcloud-configCenter\s # 可以使用这个配置项来指定本地git仓库的路径  不指定会默认在c盘  每次请求时会先从git上拉取到本地
    label: master  #默认分支  访问的时候可带分支名   http://localhost:5000/dev/consumer-dev.yml
  #使用rabbitmq来通知多个服务之间获取config的配置文件刷新，不然每个服务掉一次接口很费劲
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/ #http://admin:123@localhost:8000/eureka/   #集群 http://localhost:8001/eureka/,http://localhost:8002/eureka/,http://localhost:8000/eureka/4

#开启所有上报端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      enabled: true
